{% set name = "nwbinspector" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc6ca28d5620d284987c9e32d3de9741ba342615029018b77f9c59d08b02448e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nwbinspector = nwbinspector._nwbinspector_cli:_nwbinspector_cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - aiohttp
    - click
    - fsspec
    - hdmf_zarr
    - jsonschema
    - natsort
    - packaging
    - pynwb >=2.8
    - PyYAML
    - requests
    - tqdm
    - isodate

test:
  requires:
    - pytest
    - pytest-cov
    - python {{ python_min }}
  source_files:
    - tests
  imports:
    - nwbinspector
  commands:
    - pytest

about:
  home: https://github.com/NeurodataWithoutBorders/nwbinspector
  summary: Tool to inspect NWB files for best practices compliance
  description: |
    Inspect NWB files for compliance with NWB Best Practices.  This inspector
    is meant as a companion to the pynwb validator, which checks for strict
    schema compliance.  In contrast, this tool attempts to apply some common
    sense to find components of the file that are technically compliant, but
    probably incorrect, or suboptimal, or deviate from best practices.  This
    tool is meant simply as a data review aid.  It does not catch all best
    practice violations, and any warnings it does produce should be checked by
    a knowledgeable reviewer.
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  doc_url: https://nwbinspector.readthedocs.io
  dev_url: https://github.com/NeurodataWithoutBorders/nwbinspector

extra:
  recipe-maintainers:
    - stephprince
    - jwodder
    - yarikoptic
    - CodyCBakerPhD
    - rly
