{% set name = "nwbinspector" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8162704dbd828588422930f0c8ac2a225e3a040e1f726df9878c3e14e15ee04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - nwbinspector = nwbinspector._inspection_cli:_inspect_all_cli

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - aiohttp
    - click
    - fsspec
    - jsonschema
    - natsort
    - numpy >=1.20.0, <2.0.0
    - packaging
    - pynwb
    - PyYAML
    - s3fs
    - requests
    - tqdm
    - isodate

test:
  requires:
    - pytest
    - pytest-cov
  source_files:
    - tests
  imports:
    - nwbinspector
  commands:
    - pytest

about:
  home: https://github.com/NeurodataWithoutBorders/nwbinspector
  summary: Tool to inspect NWB files for best practices compliance
  description: |
    Inspect NWB files for compliance with NWB Best Practices.  This inspector
    is meant as a companion to the pynwb validator, which checks for strict
    schema compliance.  In contrast, this tool attempts to apply some common
    sense to find components of the file that are technically compliant, but
    probably incorrect, or suboptimal, or deviate from best practices.  This
    tool is meant simply as a data review aid.  It does not catch all best
    practice violations, and any warnings it does produce should be checked by
    a knowledgeable reviewer.
  license: BSD-3-Clause
  license_family: BSD
  license_file: license.txt
  doc_url: https://nwbinspector.readthedocs.io
  dev_url: https://github.com/NeurodataWithoutBorders/nwbinspector

extra:
  recipe-maintainers:
    - stephprince
    - jwodder
    - yarikoptic
    - CodyCBakerPhD
